GET http://localhost:4000/cards

###
POST http://localhost:4000/cards
Content-Type: application/json

{
  "title": "Je suis une jolie petite carte",
  "content": "je suis le contenu de la jolie petite carte",
  "list_id": 1
}
###
POST http://localhost:4000/cards
Content-Type: application/json

{
  "title":"Je suis une très jolie petite liste",
  "position": 5
}
###
POST http://localhost:4000/cards
Content-Type: application/json

{
  "position": 5
}
###
POST http://localhost:4000/cards
Content-Type: application/json

{
  "title":"Je suis une très jolie petite liste",
  "position": "Quesadillas"
}
###
GET http://localhost:4000/cards/2
###
GET http://localhost:4000/cards/544654
###
GET http://localhost:4000/cards/blob
###
PATCH http://localhost:4000/cards/2
Content-Type: application/json

{
  "title":"Nouveau titre"
}
###
PATCH http://localhost:4000/cards/2
Content-Type: application/json

{
  "position":54
}
###
PATCH http://localhost:4000/cards/2
Content-Type: application/json

{
  "title":321
}
###
PATCH http://localhost:4000/cards/2
Content-Type: application/json

{
  "title":"titre plus mieux",
  "position": "Joe"
}
###
PATCH http://localhost:4000/cards/2
Content-Type: application/json

{

}
###
PATCH http://localhost:4000/cards/354654
Content-Type: application/json

{

}
###
DELETE  http://localhost:4000/cards/1
###
DELETE  http://localhost:4000/cards/jack
###
DELETE  http://localhost:4000/cards/666

###
PUT http://localhost:4000/cards/2/tags/2
###
DELETE http://localhost:4000/cards/2/tags/2
###
PUT http://localhost:4000/cards/650/tags/2
###
DELETE http://localhost:4000/cards/2/tags/322
###
PUT http://localhost:4000/cards/joe/tags/2
###
DELETE http://localhost:4000/cards/2/tags/jack

