GET http://localhost:4000/tags

###
POST http://localhost:4000/tags
Content-Type: application/json

{
  "name": "à discuter"
}
###
POST http://localhost:4000/tags
Content-Type: application/json

{
  "name": 5
}
###
POST http://localhost:4000/tags
Content-Type: application/json

{
  "name":"à tester",
  "color": "Quesadillas"
}
###
GET http://localhost:4000/tags/2
###
GET http://localhost:4000/tags/544654
###
GET http://localhost:4000/tags/blob
###
PATCH http://localhost:4000/tags/2
Content-Type: application/json

{
  "title":"Nouveau titre"
}
###
PATCH http://localhost:4000/tags/2
Content-Type: application/json

{
  "position":54
}
###
PATCH http://localhost:4000/tags/2
Content-Type: application/json

{
  "title":321
}
###
PATCH http://localhost:4000/tags/2
Content-Type: application/json

{
  "title":"titre plus mieux",
  "position": "Joe"
}
###
PATCH http://localhost:4000/tags/2
Content-Type: application/json

{

}
###
PATCH http://localhost:4000/tags/354654
Content-Type: application/json

{

}
###
DELETE  http://localhost:4000/tags/1
###
DELETE  http://localhost:4000/tags/jack
###
DELETE  http://localhost:4000/tags/666

